### ISSUE TITLE
Integration not able to fetch device status on startup or reload

### ISSUE THREAD

**Issue by uddinkayyum** [tuya/tuya-smart-life#10]
After pairing device with homeassistant via HACS, devices show it integration but can't control.
One more thing, change device name in smartlife app immediately reflect in Homeassistant.
Device is turn on but still showing unavailable.
![Screenshot from 2023-10-30 14-45-08](https://github.com/tuya/tuya-smart-life/assets/94560388/56dc564c-ee9c-46f3-8e79-02ce6f17e4b4)
![Screenshot from 2023-10-30 14-45-27](https://github.com/tuya/tuya-smart-life/assets/94560388/73fcaae7-421b-4767-bb19-dbcb04a77f7e)

**Comment by shihuimiao** [comment]
Download diagnostics and check if online. If true, try to reload the smartlife integration.

**Comment by uddinkayyum** [comment]
Seems like older firmware devices working with some minor issue(light in on but homeassistant showing off status), newer firmware able to connect but can't get status.
![Screenshot from 2023-10-30 15-43-47](https://github.com/tuya/tuya-smart-life/assets/94560388/6d2c48ff-126b-4beb-861a-d159b991fc9e)
![Screenshot from 2023-10-30 15-44-21](https://github.com/tuya/tuya-smart-life/assets/94560388/78239a1f-72c7-40f6-b2a3-0aa4367c8afb)

**Comment by uddinkayyum** [comment]
Additional Developer states
![Screenshot from 2023-10-30 15-53-29](https://github.com/tuya/tuya-smart-life/assets/94560388/e84721d8-981f-494b-a651-2dc2e27d0ad6)

**Comment by uddinkayyum** [comment]
manually setting light state to "on" via Homeassistant Developer tools working well for both light.

**Comment by shihuimiao** [comment]
Can you provide the diagnostics file?

**Comment by uddinkayyum** [comment]
Figure out issue, when device is already in "on" state and if Smartlife integration reload then Tuya devices marked as "unavailable". Also, "unavailable" device can't be control using Homeassistant UI.
For resolving issue, at startup Smartlife integration need to fetch device status once to work properly.

**Comment by uddinkayyum** [comment]
> Figure out issue, when device is already in "on" state and if Smartlife integration reload then Tuya devices marked as "unavailable". Also, "unavailable" device can't be control using Homeassistant UI. For resolving issue, at startup Smartlife integration need to fetch device status once to work properly.

Note: Both firmware device working well, if i power-on device after integration load.

**Comment by capsel22** [comment]
Same thing for me.
HA restart or integration reload will return HA showing as the switches being "ON" even though smartlife app shows them as "OFF"
![Screenshot_2023-10-31-11-43-36-60_a3b3f7ff182fbca1933b088238f0f0da](https://github.com/tuya/tuya-smart-life/assets/38831192/d2fbea7d-cca7-4de0-bad6-8f9df53fcd90)

Not sure what else or how to supply more information

**Comment by gsqqq123** [comment]
![企业微信截图_d30e2843-b031-43ca-be35-1e0a243beed3](https://github.com/tuya/tuya-smart-life/assets/11343923/a01e413c-8c50-4375-8cd2-071d1f328db5)

**Comment by uddinkayyum** [comment]
[smartlife-7d0fc38828ff53f00eb5cac8b1031a18-l2-kitchen-light-66e01ebaeca749e7be682bdd20b243c2.json.txt](https://github.com/tuya/tuya-smart-life/files/13253569/smartlife-7d0fc38828ff53f00eb5cac8b1031a18-l2-kitchen-light-66e01ebaeca749e7be682bdd20b243c2.json.txt)
https://youtu.be/2-1_TTcPN6k

**Comment by shihuimiao** [comment]
> [smartlife-7d0fc38828ff53f00eb5cac8b1031a18-l2-kitchen-light-66e01ebaeca749e7be682bdd20b243c2.json.txt](https://github.com/tuya/tuya-smart-life/files/13253569/smartlife-7d0fc38828ff53f00eb5cac8b1031a18-l2-kitchen-light-66e01ebaeca749e7be682bdd20b243c2.json.txt) https://youtu.be/2-1_TTcPN6k Issue persist until i manually power cycle device from tuya app.

Locally tested the Halonix Prizm WiFi Bulb, which has no issues. Fixed the issue of obtaining new device status. Please download the smartlife plugin code again and integrate it again

**Comment by uddinkayyum** [comment]
update to version "fae5fd7" problem still exit
![Screenshot from 2023-11-06 11-17-25](https://github.com/tuya/tuya-smart-life/assets/94560388/17ea984a-0aec-43f5-94f2-ff0e7e560b9d)

**Comment by uddinkayyum** [comment]
this is not my issue "Fixed the issue of obtaining new device status", my issue is "device status unknown after integration startup".
to fix this issue do something which call device or tuya server to fetch current status, otherwise for temporary patch marked device status as "off".
my workaround for fix this issue has, i write a script in homeassistant which marked device status as off after homeassistant startup.

**Comment by uddinkayyum** [comment]
Note: if i control device using homeasssistant "**service call**", even if device show "**This entity is no longer being provided by the smartlife integration. If the entity is no longer in use, delete it in settings.**". Then this issue never exist "**Integration not able to fetch device status on startup or reload
#10** "

**Comment by shihuimiao** [comment]
> Figure out issue, when device is already in "on" state and if Smartlife integration reload then Tuya devices marked as "unavailable". Also, "unavailable" device can't be control using Homeassistant UI. For resolving issue, at startup Smartlife integration need to fetch device status once to work properly.

reload the Smartlife integration already fetch device status, What version of Home Assistant Core has the issue?

**Comment by shihuimiao** [comment]
Interface return value type error fixed, please reload the smartlife integration try again.

**Comment by uddinkayyum** [comment]
issue fixed
