### ISSUE TITLE
led_strip_wifi_ble_RGB only has Binary entity

### ISSUE THREAD

**Issue by WayneStallwood** [tuya/tuya-smart-life#11]
I've set up the integration for my led_strip_wifi_ble_RGB and all is good, Colour picker and brightness levels all work as expected from HA in Lovelace.

However the only device entity I have is a binary state, device only shows one entity which is the on/off switch.

I would like to use HA Automations to adjust brightness and colour automatically...HA knows how to set this in the integration as the panel works in Lovelace...but without a set of entites for brightness and colour I can't do anything other than turn the light on or off with the automations.

**Comment by shihuimiao** [comment]
Questions about entities can be fed back to HA’s official tuya integration. smartlife will not change the relevant entity codes for the time being.
