### ISSUE TITLE
Error add  E27 RGB + CCT WiFi Smart Led Bulb 10W Tuya

### ISSUE THREAD

**Issue by m-larin** [tuya/tuya-smart-life#12]
After add Tuya Bulb devise marked as unavalible and in log error:

Exception in async_write_ha_state when dispatching 'smartlife_entry_update_bf3d4ffdb31eb33e407dpo': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state state, attr = self._async_generate_attributes() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes attr.update(self.state_attributes or {}) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1021, in state_attributes data[ATTR_BRIGHTNESS] = self.brightness ^^^^^^^^^^^^^^^ File "/config/custom_components/smartlife/light.py", line 609, in brightness brightness = self._brightness.remap_value_to(brightness) ^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smartlife/base.py", line 63, in remap_value_to return remap_value(value, self.min, self.max, to_min, to_max, reverse) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smartlife/util.py", line 16, in remap_value return ((value - from_min) / (from_max - from_min)) * (to_max - to_min) + to_min ~~~~~~^~~~~~~~~~ TypeError: unsupported operand type(s) for -: 'str' and 'int'

Diagnostics file:
[smartlife-88b66dbb0e2445abc9abb943a06522a0-WiFi Smart Bulb-a35deda8ca163f39e913cc77edc36c1e.json.txt](https://github.com/tuya/tuya-smart-life/files/13213655/smartlife-88b66dbb0e2445abc9abb943a06522a0-WiFi.Smart.Bulb-a35deda8ca163f39e913cc77edc36c1e.json.txt)

**Comment by shihuimiao** [comment]
Fixed. Please download the smartlife plugin code again and integrate it again

**Comment by m-larin** [comment]
It worked, thanks!
