### ISSUE TITLE
moes zigbee hub unsupported

### ISSUE THREAD

**Issue by kurtdefeyter** [tuya/tuya-smart-life#14]
Hi ,
The following device appears as unsupported https://nl.aliexpress.com/item/1005004531398998.html?spm=a2g0o.order_list.order_list_main.36.191079d21lN06i&gatewayAdapt=glo2nld 
![afbeelding](https://github.com/tuya/tuya-smart-life/assets/125728797/7efd9d30-4b8d-445b-a179-f8462cb525de)
[smartlife-4cc0cdebfd45d1b7f1cf062cd927bb78-Gateway-e4d6664a033bb51072fc05783d96dc35.json.txt](https://github.com/tuya/tuya-smart-life/files/13236032/smartlife-4cc0cdebfd45d1b7f1cf062cd927bb78-Gateway-e4d6664a033bb51072fc05783d96dc35.json.txt)

**Comment by shihuimiao** [comment]
here is no entity supporting the category "wg2"

**Comment by kurtdefeyter** [comment]
Is this going to be implemented ?

**Comment by gsqqq123** [comment]
Sorry, there are currently no plans to implement it. Our strategy is to maintain the existing supported categories. If you need it, you can develop it yourself and merge the feature code.
