### ISSUE TITLE
Water Valve controller, unsupported

### ISSUE THREAD

**Issue by capsel22** [tuya/tuya-smart-life#15]
Hi,
I've got a water valve controller which is connected to a gateway over Bluetooth. I can see the device in HA, however it shows as unsupported and has no entities. It works as expected on Smartlife app.
Is there a way to have on/off button for this device so that I can control it inside HA, please?

Attaching the "Device Diagnostics", let me know if there is anything else

![image](https://github.com/tuya/tuya-smart-life/assets/38831192/f5e4bb8c-ae38-4f8e-81de-67dc89669ea7)
[smartlife-99b47ecca167acefa0709f5abae6cd4a-Valve Controller-db74c1fa9080fc590c45a5a6ade8d189.json.txt](https://github.com/tuya/tuya-smart-life/files/13256109/smartlife-99b47ecca167acefa0709f5abae6cd4a-Valve.Controller-db74c1fa9080fc590c45a5a6ade8d189.json.txt)

**Comment by gsqqq123** [comment]
Sorry, this category is currently not supported
