### ISSUE TITLE
Unable to open IPC Camera video stream

### ISSUE THREAD

**Issue by Delwin98** [tuya/tuya-smart-life#18]
Unable to open IPC Camera video stream.

In logs:
`Logger: homeassistant.components.stream.stream.camera.ipc_none
Source: components/stream/__init__.py:431
Integration: Stream (documentation, issues)
First occurred: 18:25:41 (29 occurrences)
Last logged: 19:31:33

Error from stream worker: Stream ended; no additional packets
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://****:****@wework-5-eu.stream.iot-11.com:443/v1/bfb94622c3f2900ea0tloz/cl3r379int5m4f82pbm09ckDm4YKJq4X?signInfo=kLOCpE2BqAnrSyf0BvFsi0WVRhOhh2VJ-gJlhiHukB_XIMTos30M4ZlH4apat_B0ucTOUqvPt6Z7LtB38hLp718u_dPtp6eJMBHYEHxJWVafAiSy0rGtnpUMAdQYq5v4vc4fFUOTt5f98ZLAWqbA3gSiAPKqTtFoXzRTnHSP4hU`

**Comment by Delwin98** [comment]
the stream stops working after a few minutes. Reloading the plugin fixes the stream. Based on the logs I see, it looks to me that there is a parameter signInfo with some kind of a token that probably doesn't get refreshed? Might be a hint, might not. Hope for a fix

**Comment by gsqqq123** [comment]
Can you provide the diagnostics file?

**Comment by Delwin98** [comment]
[smartlife-59a14ad77c1bf4b2b765c0fe5f8c0ce8-Камера-6a0033e48abed8ebd9b0462f8a63db9c.json](https://github.com/tuya/tuya-smart-life/files/13271976/smartlife-59a14ad77c1bf4b2b765c0fe5f8c0ce8-.-6a0033e48abed8ebd9b0462f8a63db9c.json)
Diagnostics file

**Comment by gsqqq123** [comment]
Currently the way to obtain video stream through the URL provided by Cloud has a validity period of 30 seconds and the maximum streaming time is 10 minutes.

**Comment by parkflyer** [comment]
Will this be extended in the future?
With this given limitations the camera integration is not very useful…
Thanks in advance,
parkflyer

**Comment by gsqqq123** [comment]
Sorry, there is currently no plan to support it.
