### ISSUE TITLE
Errors while setting up smartlife platform for domain light

### ISSUE THREAD

**Issue by sleavitt** [tuya/tuya-smart-life#19]
New installation from GitHub repo through HACS, getting the following error messages with Geeni light bulbs (Merkury BW942 Smart Bulb) successfully set up in SmartLife mobile app:

1. Error while setting up smartlife platform for light:

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:367
Integration: Light (documentation, issues)
First occurred: 4:45:55 PM (1 occurrences)
Last logged: 4:45:55 PM

Error while setting up smartlife platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1020, in state_attributes
    data[ATTR_BRIGHTNESS] = self.brightness
                            ^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/light.py", line 609, in brightness
    brightness = self._brightness.remap_value_to(brightness)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/base.py", line 63, in remap_value_to
    return remap_value(value, self.min, self.max, to_min, to_max, reverse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/util.py", line 16, in remap_value
    return ((value - from_min) / (from_max - from_min)) * (to_max - to_min) + to_min
             ~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'

---

2. Error adding entities for domain light with platform smartlife:

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:507
Integration: Light (documentation, issues)
First occurred: 4:45:55 PM (1 occurrences)
Last logged: 4:45:55 PM

Error adding entities for domain light with platform smartlife
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1020, in state_attributes
    data[ATTR_BRIGHTNESS] = self.brightness
                            ^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/light.py", line 609, in brightness
    brightness = self._brightness.remap_value_to(brightness)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/base.py", line 63, in remap_value_to
    return remap_value(value, self.min, self.max, to_min, to_max, reverse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/util.py", line 16, in remap_value
    return ((value - from_min) / (from_max - from_min)) * (to_max - to_min) + to_min
             ~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by sleavitt** [comment]
Diagnostic files from Home Assistant for each device are attached:

- [smartlife-e25a5b42b4e872451dac434f35809e77-Garage Front Light 2-504f2924c6d7ade340796acb73e72e71.json.txt](https://github.com/tuya/tuya-smart-life/files/13261176/smartlife-e25a5b42b4e872451dac434f35809e77-Garage.Front.Light.2-504f2924c6d7ade340796acb73e72e71.json.txt)
- [smartlife-e25a5b42b4e872451dac434f35809e77-Garage Front Light 1-5074a12142d7c717163921d08b6bb21b.json.txt](https://github.com/tuya/tuya-smart-life/files/13261177/smartlife-e25a5b42b4e872451dac434f35809e77-Garage.Front.Light.1-5074a12142d7c717163921d08b6bb21b.json.txt)
- [smartlife-e25a5b42b4e872451dac434f35809e77-Front Porch Light-ad6ed995cf0e9cd07abddf0e5c97732f.json.txt](https://github.com/tuya/tuya-smart-life/files/13261178/smartlife-e25a5b42b4e872451dac434f35809e77-Front.Porch.Light-ad6ed995cf0e9cd07abddf0e5c97732f.json.txt)

**Comment by shihuimiao** [comment]
Fixed. Please download the smartlife plugin code again and integrate it again

**Comment by sleavitt** [comment]
Removed integration from Home Assistant and HACS, reinstalled as custom
repository from HACS and set integration back up per directions. No change
in behavior; bulbs are detected by the smartlife integration, but show up
as unavailable. Also, neither the tuya-smart-life nor the
tuya-device-sharing-sdk show any changes from within the last 5 days.

**Comment by shihuimiao** [comment]
Tested this product and did not find the problem you mentioned. Can you open the debug mode for logs, send me the debug log.

**Comment by sleavitt** [comment]
I hope this is what you are looking for, I enabled debug logging in smartlife. Please let me know if you need anything further.

[home-assistant_2023-11-07T18-21-26.595Z.log](https://github.com/tuya/tuya-smart-life/files/13284600/home-assistant_2023-11-07T18-21-26.595Z.log)

**Comment by sleavitt** [comment]
I've set up Visual Studio Code and using the HA devcontainer, I can see that the value reaching the remap_value function in util.py is '255' as a string, not as an integer, which explains the error, in that you can't subtract an int from a string in Python. The question, I guess, is where is the '255' value coming from, and why is it a string and not an int or float?

**Comment by sleavitt** [comment]
I can confirm that the following change in class IntegerTypeData in base.py addresses this issue for me and the entities are now available and I am able to control them (though their initial state appears to be incorrect, which is another issue):

```python
diff --git a/custom_components/smartlife/base.py b/custom_components/smartlife/base.py
index cc76e23..7e08377 100644
--- a/custom_components/smartlife/base.py
+++ b/custom_components/smartlife/base.py
@@ -60,7 +60,7 @@ class IntegerTypeData:
             reverse: bool = False,
     ) -> float:
         """Remap a value from this range to a new range."""
-        return remap_value(value, self.min, self.max, to_min, to_max, reverse)
+        return remap_value(float(value), self.min, self.max, to_min, to_max, reverse)

     def remap_value_from(
             self,
@@ -70,7 +70,7 @@ class IntegerTypeData:
             reverse: bool = False,
     ) -> float:
         """Remap a value from its current range to this range."""
-        return remap_value(value, from_min, from_max, self.min, self.max, reverse)
+        return remap_value(float(value), from_min, from_max, self.min, self.max, reverse)

     @classmethod
     def from_json(cls, dpcode: DPCode, data: str) -> IntegerTypeData | None:
``` 

Whether or not this is the best fix, I do not know, but casting the values to floats based on the type hinting in the remap_values_from and remap_values_to functions seemed like the right thing to do here, given that this represents the IntegerDataClass, and as such it is reasonable to expect that an integer value is what should be returned here.

**Comment by shihuimiao** [comment]
Interface return value type error fixed, please reload the smartlife integration try again.

**Comment by sleavitt** [comment]
I'd be happy to reload it, but I'm not seeing anything new in either of the "tuya-smart-life" or "tuya-device-sharing-sdk" GitHub repositories. Please advise where I should reload the integration from, thanks.

![image](https://github.com/tuya/tuya-smart-life/assets/76140/33e699b4-6f57-4ada-8534-43fed3fe0f31)
![image](https://github.com/tuya/tuya-smart-life/assets/76140/82b393f7-e75d-4928-b231-28a471d3c14c)

**Comment by shihuimiao** [comment]
It's the issue with the interface data type we provided, It's not related to smartlife integration.
reload can work.
