### ISSUE TITLE
Tuya curtains become unavailable after adding them in HA

### ISSUE THREAD

**Issue by vladab** [tuya/tuya-smart-life#21]
Hi after pairing the app and successfully adding curtains from the smart life app, they are not available to control.

Devices are controllable from the smart life app on the iPad, but not controllable after adding them in HA. I have tried multiple times to remove smartlife from HACS, restarting it, reading, etc.

Maybe it's similar to this issue as well:
[Integration not able to fetch device status on startup or reload ](https://github.com/tuya/tuya-smart-life/issues/10)

Diagnostics file:
[smartlife-dacc79a7d837e1f8dd010fa099730156-Wifi Roller Shade Converter 5-1e622b7585bea5c222249cbe5337f5f3.json.txt](https://github.com/tuya/tuya-smart-life/files/13267095/smartlife-dacc79a7d837e1f8dd010fa099730156-Wifi.Roller.Shade.Converter.5-1e622b7585bea5c222249cbe5337f5f3.json.txt)

<img width="1218" alt="Screenshot 2023-11-06 at 14 35 46" src="https://github.com/tuya/tuya-smart-life/assets/7256398/80f876b9-e984-4131-bc19-41f492f2e887">
<img width="567" alt="Screenshot 2023-11-06 at 14 38 42" src="https://github.com/tuya/tuya-smart-life/assets/7256398/b1a32371-6b71-4377-89f9-3717174d8268">
<img width="1008" alt="Screenshot 2023-11-06 at 14 42 17" src="https://github.com/tuya/tuya-smart-life/assets/7256398/09307673-0208-4f12-80da-68660bc44256">
<img width="430" alt="Screenshot 2023-11-06 at 14 42 28" src="https://github.com/tuya/tuya-smart-life/assets/7256398/5db4b620-e001-40f5-b301-50781b1247e4">

**Comment by shihuimiao** [comment]
Same device, different entities, some unavailable, some available? What version of Home Assistant Core has the issue?

**Comment by vladab** [comment]
It happens to all of 5 them, I have just one type of device, curtains. They appear as 5 devices and 10 entities once they initialise. They are successfully added in the HA, but they appear as unavailable. I have the latest version of HA, the smartlife plugin is the latest in HACS.

<img width="628" alt="Screenshot 2023-11-07 at 10 50 04" src="https://github.com/tuya/tuya-smart-life/assets/7256398/d22d279b-abaa-4a25-aacc-af689cbe4255">

<img width="1015" alt="Screenshot 2023-11-07 at 10 53 46" src="https://github.com/tuya/tuya-smart-life/assets/7256398/6a3a2f3d-5315-4527-b2de-f484bde33697">

**Comment by vladab** [comment]
There are some additional errors in the debug log

[home-assistant_smartlife_2023-11-07T09-57-37.474Z.log](https://github.com/tuya/tuya-smart-life/files/13278487/home-assistant_smartlife_2023-11-07T09-57-37.474Z.log)

**Comment by shihuimiao** [comment]
Interface return value type error fixed, please reload the smartlife integration try again.
Thank you for providing the debug log.

**Comment by vladab** [comment]
Works now, thanks!
