### ISSUE TITLE
URL "https://brands.home-assistant.io/smartlife/icon.png" is broken (returns 404)

### ISSUE THREAD

**Issue by sleavitt** [tuya/tuya-smart-life#23]
Minor cosmetic thing, but the title says it all. "https://brands.home-assistant.io/smartlife/icon.png" returns a 404 Not Found.

**Comment by shihuimiao** [comment]
We haven't uploaded the icon yet.

**Comment by VenoushCZ** [comment]
Is it planned?

**Comment by shihuimiao** [comment]
Beta version will not be uploaded.
