### ISSUE TITLE
Power monitoring plugs are sluggish at updating sensors

### ISSUE THREAD

**Issue by mattwildingithub** [tuya/tuya-smart-life#26]
Sensors for Voltage / Current  / Power on power monitoring plugs are sluggish at updating their values - sometimes taking several minutes to register a change  - for info, this is the exact same behaviour across the 'official' Tuya Home Assistant integration, and also in the Tuya IoT dashboard. They all update at the same time with the same delays. The delays are also inconsistent. This makes power monitoring automations impossible.

*unless*

...you have the Smart Life app open on your phone with the plug open > 'Electric', then the values across all integrations and IoT update live. No delays at all.

Home Assistant
Core 2023.11.2
Supervisor 2023.11.0
Operating System 11.1
Frontend 20231030.2

**Comment by ZyborgRSA** [comment]
Having the same problem, 1 Plug is updating often, rest have large gaps between updates, if they update at all, but if I open the app and go to the Electricity graph for that plug, it updates every 10 seconds or so in HA.

**Comment by mattwildingithub** [comment]
If anyone finds this and needs a workaround, I installed the LocalTuya integration (via HACS) alongside the other Tuya integrations. I added the just the plug I wanted to monitor (which was all massively long winded and complicated) and you can set the devices' polling time - which I set to 15 seconds. Now the plug reports its values to * all * integrations and the IOT dashboard every 15 seconds. So I guess if they added a 'polling time' option into the tuya smart life Int, then that would fix it? dunno. but it worked for me. not ideal. but seems to work. ymmv.
