### ISSUE TITLE
Tuya Multi Channel Weather Station - no entities for extra channels

### ISSUE THREAD

**Issue by verticalperformance** [tuya/tuya-smart-life#28]
The issue with additional sensors not being exposed in Multi Channel Temperature and Humidity sensors as reported in previous Tuya integration does not appear to be addressed yet in the new integration.

See:
https://github.com/tuya/tuya-home-assistant/issues/902#issuecomment-1402425903

**Comment by shihuimiao** [comment]
smartlife only changes the underlying SDK and does not involve entity modification. sorry
