### ISSUE TITLE
Device found but does not show entities - QS-WIFI-CT02 2 way clamp meter

### ISSUE THREAD

**Issue by kris5432** [tuya/tuya-smart-life#29]
# WHAT 
Installed the integration, most devices show up as expected, but I have "2 Gang WIFI Single Phase Clamp Meter" that reports values perfectly on the smartlife app on Android, but shows as unsupported on homeassistant using this integration. 

Device Model: QS-WIFI-CT02
product_name: "Double Digital Meter"

Shows as Double Digital Meter (unsupported) by smartlife

Can you please help me add the proper entities to this device? 
Is there a process I should follow? 

Let me know if you need further details.

**Comment by shihuimiao** [comment]
HA will not support all entities.
