### ISSUE TITLE
Thermostat units

### ISSUE THREAD

**Issue by lupus78** [tuya/tuya-smart-life#30]
I tried this and the offical Tuya integration, and in both I have this issue:
Device details:
Product Name: HY08WE最新通用型
Product Category: wk

the Entities has this state (first is the tuya integration, the second is smart-life integration)
![image](https://github.com/tuya/tuya-smart-life/assets/5301520/2afbdbee-7f92-48a2-ad03-ac2d8694fa07)

I'm using it in Celcius in the SmartLife mobile app, and there the temperature range is 5 to 35C, with 0.5C increments.
But from my HA Entity state you can see it's 0.5C to 70C, with 0.1 Increments. This makes the HA's thermostat card act weirdly. Steps will be 0.1C, but after changing round it down to the nearest 0.5C, eg: setting 22.9C will jump to 22.5C.
Also the slider with max 70C is way to high, and because of the 0.1C increment dragging the value is very inconvenient.

I would be fantastic to see when the Thermostat is heating state or not. I think this is a very important information missing. It can only be checked in the SmartLife mobile app?

**Comment by shihuimiao** [comment]
the offical Tuya integration, and in both I have this issue, you can mention issues to HA off official. 
We have temporarily replaced the underlying SDK here.
