### ISSUE TITLE
PIR motion sensor still unsupported

### ISSUE THREAD

**Issue by grampasso-lento** [tuya/tuya-smart-life#31]
Imported device from Tuya into smartlife. PIR sensors (motion sensors) still do not appear correctly (the device has no entity). Same was happening in Tuya integrations. These devices are identified  by Tuya as WS-02.
Moreover, all imported devices in smartlife are labeled unsupported, in Tuya only WS-02 devices were labelled unsupported.
Example: entity Cucina-f16-east, smartlife, Door Sensor (unsupported).

Diagnostic for the entity:
      {
        "id": "xxxxxxxx", (obscured)
        "name": "Cucina-f16-est",
        "category": "mcs",
        "product_id": "3if4nqvwbkybeu3z",
        "product_name": "Door Sensor",
        "online": true,
        "sub": true,
        "time_zone": "+02:00",
        "active_time": "2022-04-07T20:33:04+00:00",
        "create_time": "2022-04-07T20:33:04+00:00",
        "update_time": "2022-04-07T20:33:04+00:00",
        "function": {},
        "status_range": {
          "doorcontact_state": {
            "type": "Boolean",
            "value": {}
          }
        },
        "status": {
          "doorcontact_state": false
        },
        "home_assistant": {
          "name": "Cucina-f16-est",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": [
            {
              "disabled": false,
              "disabled_by": null,
              "entity_category": null,
              "device_class": null,
              "original_device_class": "door",
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": null,
              "state": {
                "entity_id": "binary_sensor.cucina_f16_est_porta",
                "state": "off",
                "attributes": {
                  "device_class": "door",
                  "friendly_name": "Cucina-f16-est Porta"
                },
                "last_changed": "2023-11-16T18:08:02.093671+00:00",
                "last_updated": "2023-11-16T18:08:02.093671+00:00"
              }
            }
          ]
        },
        "set_up": true,
        "support_local": true
      },

**Comment by gsqqq123** [comment]
Sorry, this category is currently not supported. If you need support, you can develop it yourself.
