### ISSUE TITLE
climate contorl error 

### ISSUE THREAD

**Issue by mickey50** [tuya/tuya-smart-life#32]
the climate can only turn off from the UI, can not turn on 
and have two same  heat/cool icon
![image](https://github.com/tuya/tuya-smart-life/assets/6166901/8196fbec-3858-4c91-ab17-1204d81de99d)
and the max_temp attr is error
the status of climate :
hvac_modes:
  - "off"
  - heat_cool
  - heat_cool
min_temp: 5
max_temp: 70
target_temp_step: 1
current_temperature: 18.5
temperature: 17
friendly_name: 智能温控器 None
supported_features: 1

**Comment by mickey50** [comment]
and mesasge from tuya iot :
功能描述 | Code | 类型 | 取值范围
-- | -- | -- | --
开关 | switch | Boolean | "{true,false}"
工作模式 | mode | Enum | {   "range": [     "auto",     "manual"   ] }
防霜冻功能 | frost | Boolean | "{true,false}"
温度设置 | temp_set | Integer | {   "unit": "℃",   "min": 5,   "max": 70,   "scale": 0,   "step": 1 }
设置温度上限 | upper_temp | Integer | {   "unit": "℃",   "min": 20,   "max": 70,   "scale": 0,   "step": 1 }
设置温度下限 | lower_temp | Integer | {   "unit": "℃",   "min": 5,   "max": 20,   "scale": 0,   "step": 1 }
温度校准 | temp_correction | Integer | {   "unit": "摄氏度",   "min": -9,   "max": 9,   "scale": 0,   "step": 1 }
恢复出厂设置 | factory_reset | Boolean | "{true,false}"
童锁 | child_lock | Boolean | "{true,false}"
传感器选择 | sensor_choose | Enum | {   "range": [     "in",     "out"   ] }


功能描述 | Code | 类型 | 取值范围
-- | -- | -- | --
开关 | switch | Boolean | "{true,false}"
工作模式 | mode | Enum | {   "range": [     "auto",     "manual"   ] }
防霜冻功能 | frost | Boolean | "{true,false}"
温度设置 | temp_set | Integer | {   "unit": "℃",   "min": 5,   "max": 70,   "scale": 0,   "step": 1 }
设置温度上限 | upper_temp | Integer | {   "unit": "℃",   "min": 20,   "max": 70,   "scale": 0,   "step": 1 }
当前温度 | temp_current | Integer | {   "unit": "℃",   "min": 0,   "max": 900,   "scale": 1,   "step": 5 }
设置温度下限 | lower_temp | Integer | {   "unit": "℃",   "min": 5,   "max": 20,   "scale": 0,   "step": 1 }
温度校准 | temp_correction | Integer | {   "unit": "摄氏度",   "min": -9,   "max": 9,   "scale": 0,   "step": 1 }
阀门状态 | valve_state | Enum | {   "range": [     "open",     "close"   ] }
恢复出厂设置 | factory_reset | Boolean | "{true,false}"
童锁 | child_lock | Boolean | "{true,false}"
传感器选择 | sensor_choose | Enum | {   "range": [     "in",     "out"   ] }
故障告警 | fault | Bitmap | {   "label": [     "e1",     "e2",     "e3"   ] }

**Comment by shihuimiao** [comment]
Can provide diagnostic file? i will test the product, If it is a UI issue, we cannot modify it here but we will provide feedback to the HA official

**Comment by mickey50** [comment]
可能是我理解错了，像上面的图那样，我的温控器显示了三个图标，最右边的电源按钮只能关闭，左边和中间的是重复的
，只能打开，我想是和这个温控器生成功能描述有关系，heat_cool重复了两遍：
hvac_modes:
"off"
heat_cool
heat_cool
我后面的回复里面贴出了很多这个温控器实现的功能，这部分可以实现么？我也试了localtuya的方式集成到HA,这些属性都可以设置来控制的，但是还有一个错误导致我不能使用：https://github.com/rospogrigio/localtuya/issues/1559 ，所以如果tuya-smart-life 是官方推荐的HA集成方式，希望能进一步完善对温控器的支持

**Comment by shihuimiao** [comment]
这次是更换账号登陆方式，不涉及插件里面的实体修改，可以先提issue到HA官方库先寻求支持，感谢

**Comment by andrus2049** [comment]
I own a Tuya/Smartlife thermostat (product_id: "9myqvomgygt9zgcs") that show similar problems in HA (tested with both this integration and the default HA Tuya integration).

Problems are mainly related to incorrect HVAC_MODEs (shown and settable), and Presets.
With the SmartLife Android app everything is fine.
Here I show the situation using the Smart Life (Beta) Home Assistant Integration.
Mode set on  IoT Tuya platform: **DP instruction**

Hope this help solving the compatibility issues with HA, thanks.

<img width="237" alt="thermostat" src="https://github.com/tuya/tuya-smart-life/assets/36678690/ad0b9940-88c4-4c05-a92e-33d235f0b116">



Here the sets from IoT Tuya platform:
---------------------------------------------------------------------
**STANDARD INSTRUCTION SET**

switch	Boolean	
"{true,false}"
mode	Enum	
{
  "range": [
    "auto",
    "holiday",
    "manual",
    "temporary"
  ]
}
temp_set	Integer	
{
  "unit": "℃",
  "min": 5,
  "max": 350,
  "scale": 1,
  "step": 1
}
upper_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
lower_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
temp_correction	Integer	
{
  "unit": "",
  "min": -30,
  "max": 30,
  "scale": 1,
  "step": 5
}
holiday_temp_set	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
holiday_days_set	Integer	
{
  "unit": "day",
  "min": 0,
  "max": 3000,
  "scale": 0,
  "step": 1
}
week_program2	Raw	
{}
factory_reset	Boolean	
"{true,false}"
child_lock	Boolean	
"{true,false}"
temporary_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 2880,
  "scale": 0,
  "step": 1
}
temp_antifreezing	Integer	
{
  "unit": "",
  "min": 5,
  "max": 150,
  "scale": 1,
  "step": 1
}
swing	Integer	
{
  "unit": "",
  "min": 2,
  "max": 20,
  "scale": 1,
  "step": 1
}
heatcool_heat_cool	Enum	
{
  "range": [
    "hc_heat",
    "hc_cool",
    "heat",
    "cool"
  ]
}
antifreezing_switch	Boolean	
"{true,false}"
use_password	Boolean	
"{true,false}"
password	Integer	
{
  "unit": "4",
  "min": 0,
  "max": 9999,
  "scale": 0,
  "step": 1
}
partial_key_lock	Boolean	
"{true,false}"

--------------------------------------------------------------
**STANDARD STATUS SET**

switch	Boolean	
"{true,false}"
mode	Enum	
{
  "range": [
    "auto",
    "holiday",
    "manual",
    "temporary"
  ]
}
work_state	Enum	
{
  "range": [
    "off",
    "heat",
    "cool"
  ]
}
temp_set	Integer	
{
  "unit": "℃",
  "min": 5,
  "max": 350,
  "scale": 1,
  "step": 1
}
upper_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
temp_current	Integer	
{
  "unit": "℃",
  "min": 0,
  "max": 400,
  "scale": 1,
  "step": 1
}
lower_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
temp_correction	Integer	
{
  "unit": "",
  "min": -30,
  "max": 30,
  "scale": 1,
  "step": 5
}
holiday_temp_set	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
holiday_days_set	Integer	
{
  "unit": "day",
  "min": 0,
  "max": 3000,
  "scale": 0,
  "step": 1
}
week_program2	Raw	
{}
factory_reset	Boolean	
"{true,false}"
child_lock	Boolean	
"{true,false}"
countdown_left	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 2880,
  "scale": 0,
  "step": 1
}
fault	Bitmap	
{
  "label": [
    "e1",
    "e2",
    "e3",
    "e4",
    "e5",
    "e6",
    "e7",
    "e8",
    "e9",
    "e10"
  ],
  "maxlen": 10
}
temporary_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 2880,
  "scale": 0,
  "step": 1
}
total_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 999999,
  "scale": 0,
  "step": 1
}
temp_antifreezing	Integer	
{
  "unit": "",
  "min": 5,
  "max": 150,
  "scale": 1,
  "step": 1
}
swing	Integer	
{
  "unit": "",
  "min": 2,
  "max": 20,
  "scale": 1,
  "step": 1
}
time_period	Integer	
{
  "unit": "",
  "min": 1,
  "max": 9,
  "scale": 0,
  "step": 1
}
electricity	Integer	
{
  "unit": "",
  "min": 0,
  "max": 6000,
  "scale": 0,
  "step": 1
}
curent_pro_time	Raw	
{}
heatcool_heat_cool	Enum	
{
  "range": [
    "hc_heat",
    "hc_cool",
    "heat",
    "cool"
  ]
}
antifreezing_switch	Boolean	
"{true,false}"
use_password	Boolean	
"{true,false}"
true_off	Boolean	
"{true,false}"
password	Integer	
{
  "unit": "4",
  "min": 0,
  "max": 9999,
  "scale": 0,
  "step": 1
}
partial_key_lock	Boolean	
"{true,false}"

----------------------------------------------------------------
**DEVICE QUERY PROPERTIES**

{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1700677459517,
        "value": true
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1700677373229,
        "value": "manual"
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 3,
        "time": 1700612410472,
        "value": "off"
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 16,
        "time": 1700678722885,
        "value": 214
      },
      {
        "code": "upper_temp",
        "custom_name": "",
        "dp_id": 19,
        "time": 1700073411555,
        "value": 240
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 24,
        "time": 1700678460970,
        "value": 217
      },
      {
        "code": "lower_temp",
        "custom_name": "",
        "dp_id": 26,
        "time": 1700073411557,
        "value": 180
      },
      {
        "code": "temp_correction",
        "custom_name": "",
        "dp_id": 27,
        "time": 1700073410634,
        "value": -15
      },
      {
        "code": "holiday_temp_set",
        "custom_name": "",
        "dp_id": 32,
        "time": 1699884863559,
        "value": 50
      },
      {
        "code": "holiday_days_set",
        "custom_name": "",
        "dp_id": 33,
        "time": 1700676000870,
        "value": 6
      },
      {
        "code": "week_program2",
        "custom_name": "",
        "dp_id": 37,
        "time": 1700072778610,
        "value": "AQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAABAAC0BgAAyAgAANIMAADSDgAA0hEAANIWAADIAAAAAAEAALQGAADICAAA0gwAANIOAADSEQAA0hYAAMgAAAAAAQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAABAAC0BgAAyAgAANIMAADSDgAA0hEAANIWAADIAAAAAAEAALQGAADICAAA0gwAANIOAADSEQAA0hYAAMgAAAAAAQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAA="
      },
      {
        "code": "factory_reset",
        "custom_name": "",
        "dp_id": 39,
        "time": 1700073411532,
        "value": true
      },
      {
        "code": "child_lock",
        "custom_name": "",
        "dp_id": 40,
        "time": 1700073411546,
        "value": false
      },
      {
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 42,
        "time": 1699884863559,
        "value": 0
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 45,
        "time": 1699884878343,
        "value": 0
      },
      {
        "code": "temporary_time",
        "custom_name": "",
        "dp_id": 101,
        "time": 1700612233350,
        "value": 60
      },
      {
        "code": "total_time",
        "custom_name": "",
        "dp_id": 102,
        "time": 1700612460272,
        "value": 2
      },
      {
        "code": "temp_antifreezing",
        "custom_name": "",
        "dp_id": 103,
        "time": 1700677460007,
        "value": 140
      },
      {
        "code": "swing",
        "custom_name": "",
        "dp_id": 104,
        "time": 1700073411552,
        "value": 3
      },
      {
        "code": "time_period",
        "custom_name": "",
        "dp_id": 105,
        "time": 1699884863559,
        "value": 1
      },
      {
        "code": "electricity",
        "custom_name": "",
        "dp_id": 106,
        "time": 1699884863559,
        "value": 0
      },
      {
        "code": "curent_pro_time",
        "custom_name": "",
        "dp_id": 107,
        "time": 1700668801980,
        "value": "EQAWAAMGAwc="
      },
      {
        "code": "heatcool_heat_cool",
        "custom_name": "",
        "dp_id": 108,
        "time": 1700073411536,
        "value": "hc_heat"
      },
      {
        "code": "antifreezing_switch",
        "custom_name": "",
        "dp_id": 109,
        "time": 1700073411860,
        "value": true
      },
      {
        "code": "use_password",
        "custom_name": "",
        "dp_id": 110,
        "time": 1700073411864,
        "value": false
      },
      {
        "code": "true_off",
        "custom_name": "",
        "dp_id": 111,
        "time": 1700678542850,
        "value": false
      },
      {
        "code": "password",
        "custom_name": "",
        "dp_id": 116,
        "time": 1700073411948,
        "value": 0
      },
      {
        "code": "partial_key_lock",
        "custom_name": "",
        "dp_id": 118,
        "time": 1700073411729,
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1700678807061,
  "tid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

-----------------------------------------

**Comment by andrus2049** [comment]
This is the diagnostics downloaded from HA:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.3",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
    "smartlife": {
      "version": "0.1.0",
      "requirements": [
        "tuya-device-sharing-sdk==0.1.8"
      ]
    }
  },
  "integration_manifest": {
    "domain": "smartlife",
    "name": "smartlife",
    "codeowners": [
      "@smartlife"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/smartlife",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "version": "0.1.0",
    "requirements": [
      "tuya-device-sharing-sdk==0.1.8"
    ],
    "is_built_in": false
  },
  "data": {
    "endpoint": "https://apigw.tuyaeu.com",
    "terminal_id": "1700173731796ygU0iP",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "name": "NEVE PRO W",
    "category": "wk",
    "product_id": "9myqvomgygt9zgcs",
    "product_name": "NEVE PRO W",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2023-11-13T14:14:23+00:00",
    "create_time": "2023-11-13T14:14:23+00:00",
    "update_time": "2023-11-13T14:14:23+00:00",
    "function": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "auto",
            "holiday",
            "manual"
          ]
        }
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 5,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "upper_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "lower_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "temp_correction": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -30,
          "max": 30,
          "scale": 1,
          "step": 5
        }
      },
      "holiday_temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "holiday_days_set": {
        "type": "Integer",
        "value": {
          "unit": "day",
          "min": 0,
          "max": 3000,
          "scale": 0,
          "step": 1
        }
      },
      "factory_reset": {
        "type": "Boolean",
        "value": {}
      },
      "child_lock": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status_range": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "auto",
            "holiday",
            "manual"
          ]
        }
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 5,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "upper_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "temp_current": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 0,
          "max": 400,
          "scale": 1,
          "step": 1
        }
      },
      "lower_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "temp_correction": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -30,
          "max": 30,
          "scale": 1,
          "step": 5
        }
      },
      "holiday_temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "holiday_days_set": {
        "type": "Integer",
        "value": {
          "unit": "day",
          "min": 0,
          "max": 3000,
          "scale": 0,
          "step": 1
        }
      },
      "factory_reset": {
        "type": "Boolean",
        "value": {}
      },
      "child_lock": {
        "type": "Boolean",
        "value": {}
      },
      "countdown_left": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 0,
          "max": 2880,
          "scale": 0,
          "step": 1
        }
      },
      "fault": {
        "type": "Bitmap",
        "value": {
          "label": [
            "e1",
            "e2",
            "e3",
            "e4",
            "e5",
            "e6",
            "e7",
            "e8",
            "e9",
            "e10"
          ]
        }
      }
    },
    "status": {
      "switch": true,
      "mode": "manual",
      "temp_set": 214,
      "upper_temp": 240,
      "temp_current": 217,
      "lower_temp": 180,
      "temp_correction": -15,
      "holiday_temp_set": 50,
      "holiday_days_set": 6,
      "factory_reset": true,
      "child_lock": false,
      "countdown_left": 0,
      "fault": 0
    },
    "home_assistant": {
      "name": "NEVE PRO W",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.neve_pro_w_none",
            "state": "heat_cool",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat_cool",
                "heat_cool",
                "heat_cool"
              ],
              "min_temp": 0.5,
              "max_temp": 35.0,
              "target_temp_step": 0.1,
              "preset_modes": [
                "holiday"
              ],
              "current_temperature": 21.7,
              "temperature": 21.4,
              "preset_mode": null,
              "friendly_name": "NEVE PRO W None",
              "supported_features": 17
            },
            "last_changed": "2023-11-22T18:33:50.114794+00:00",
            "last_updated": "2023-11-22T18:34:03.089034+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true
  }
 }

**Comment by mickey50** [comment]
> I own a Tuya/Smartlife thermostat (product_id: "9myqvomgygt9zgcs") that show similar problems in HA (tested with both this integration and the default HA Tuya integration).
> 
> Problems are mainly related to incorrect HVAC_MODEs (shown and settable), and Presets. With the SmartLife Android app everything is fine. Here I show the situation using the Smart Life (Beta) Home Assistant Integration. Mode set on IoT Tuya platform: **DP instruction**
> 
> Hope this help solving the compatibility issues with HA, thanks.
> 
> <img alt="thermostat" width="237" src="https://user-images.githubusercontent.com/36678690/285013748-ad0b9940-88c4-4c05-a92e-33d235f0b116.png">
> ## Here the sets from IoT Tuya platform:
> **STANDARD INSTRUCTION SET**
> 
> switch Boolean "{true,false}" mode Enum { "range": [ "auto", "holiday", "manual", "temporary" ] } temp_set Integer { "unit": "℃", "min": 5, "max": 350, "scale": 1, "step": 1 } upper_temp Integer { "unit": "℃", "min": 50, "max": 350, "scale": 1, "step": 1 } lower_temp Integer { "unit": "℃", "min": 50, "max": 350, "scale": 1, "step": 1 } temp_correction Integer { "unit": "", "min": -30, "max": 30, "scale": 1, "step": 5 } holiday_temp_set Integer { "unit": "℃", "min": 50, "max": 350, "scale": 1, "step": 1 } holiday_days_set Integer { "unit": "day", "min": 0, "max": 3000, "scale": 0, "step": 1 } week_program2 Raw {} factory_reset Boolean "{true,false}" child_lock Boolean "{true,false}" temporary_time Integer { "unit": "min", "min": 0, "max": 2880, "scale": 0, "step": 1 } temp_antifreezing Integer { "unit": "", "min": 5, "max": 150, "scale": 1, "step": 1 } swing Integer { "unit": "", "min": 2, "max": 20, "scale": 1, "step": 1 } heatcool_heat_cool Enum { "range": [ "hc_heat", "hc_cool", "heat", "cool" ] } antifreezing_switch Boolean "{true,false}" use_password Boolean "{true,false}" password Integer { "unit": "4", "min": 0, "max": 9999, "scale": 0, "step": 1 } partial_key_lock Boolean "{true,false}"
> 
> **STANDARD STATUS SET**
> 
> switch Boolean "{true,false}" mode Enum { "range": [ "auto", "holiday", "manual", "temporary" ] } work_state Enum { "range": [ "off", "heat", "cool" ] } temp_set Integer { "unit": "℃", "min": 5, "max": 350, "scale": 1, "step": 1 } upper_temp Integer { "unit": "℃", "min": 50, "max": 350, "scale": 1, "step": 1 } temp_current Integer { "unit": "℃", "min": 0, "max": 400, "scale": 1, "step": 1 } lower_temp Integer { "unit": "℃", "min": 50, "max": 350, "scale": 1, "step": 1 } temp_correction Integer { "unit": "", "min": -30, "max": 30, "scale": 1, "step": 5 } holiday_temp_set Integer { "unit": "℃", "min": 50, "max": 350, "scale": 1, "step": 1 } holiday_days_set Integer { "unit": "day", "min": 0, "max": 3000, "scale": 0, "step": 1 } week_program2 Raw {} factory_reset Boolean "{true,false}" child_lock Boolean "{true,false}" countdown_left Integer { "unit": "min", "min": 0, "max": 2880, "scale": 0, "step": 1 } fault Bitmap { "label": [ "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "e10" ], "maxlen": 10 } temporary_time Integer { "unit": "min", "min": 0, "max": 2880, "scale": 0, "step": 1 } total_time Integer { "unit": "min", "min": 0, "max": 999999, "scale": 0, "step": 1 } temp_antifreezing Integer { "unit": "", "min": 5, "max": 150, "scale": 1, "step": 1 } swing Integer { "unit": "", "min": 2, "max": 20, "scale": 1, "step": 1 } time_period Integer { "unit": "", "min": 1, "max": 9, "scale": 0, "step": 1 } electricity Integer { "unit": "", "min": 0, "max": 6000, "scale": 0, "step": 1 } curent_pro_time Raw {} heatcool_heat_cool Enum { "range": [ "hc_heat", "hc_cool", "heat", "cool" ] } antifreezing_switch Boolean "{true,false}" use_password Boolean "{true,false}" true_off Boolean "{true,false}" password Integer { "unit": "4", "min": 0, "max": 9999, "scale": 0, "step": 1 } partial_key_lock Boolean "{true,false}"
> 
> **DEVICE QUERY PROPERTIES**
> 
> { "result": { "properties": [ { "code": "switch", "custom_name": "", "dp_id": 1, "time": 1700677459517, "value": true }, { "code": "mode", "custom_name": "", "dp_id": 2, "time": 1700677373229, "value": "manual" }, { "code": "work_state", "custom_name": "", "dp_id": 3, "time": 1700612410472, "value": "off" }, { "code": "temp_set", "custom_name": "", "dp_id": 16, "time": 1700678722885, "value": 214 }, { "code": "upper_temp", "custom_name": "", "dp_id": 19, "time": 1700073411555, "value": 240 }, { "code": "temp_current", "custom_name": "", "dp_id": 24, "time": 1700678460970, "value": 217 }, { "code": "lower_temp", "custom_name": "", "dp_id": 26, "time": 1700073411557, "value": 180 }, { "code": "temp_correction", "custom_name": "", "dp_id": 27, "time": 1700073410634, "value": -15 }, { "code": "holiday_temp_set", "custom_name": "", "dp_id": 32, "time": 1699884863559, "value": 50 }, { "code": "holiday_days_set", "custom_name": "", "dp_id": 33, "time": 1700676000870, "value": 6 }, { "code": "week_program2", "custom_name": "", "dp_id": 37, "time": 1700072778610, "value": "AQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAABAAC0BgAAyAgAANIMAADSDgAA0hEAANIWAADIAAAAAAEAALQGAADICAAA0gwAANIOAADSEQAA0hYAAMgAAAAAAQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAABAAC0BgAAyAgAANIMAADSDgAA0hEAANIWAADIAAAAAAEAALQGAADICAAA0gwAANIOAADSEQAA0hYAAMgAAAAAAQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAA=" }, { "code": "factory_reset", "custom_name": "", "dp_id": 39, "time": 1700073411532, "value": true }, { "code": "child_lock", "custom_name": "", "dp_id": 40, "time": 1700073411546, "value": false }, { "code": "countdown_left", "custom_name": "", "dp_id": 42, "time": 1699884863559, "value": 0 }, { "code": "fault", "custom_name": "", "dp_id": 45, "time": 1699884878343, "value": 0 }, { "code": "temporary_time", "custom_name": "", "dp_id": 101, "time": 1700612233350, "value": 60 }, { "code": "total_time", "custom_name": "", "dp_id": 102, "time": 1700612460272, "value": 2 }, { "code": "temp_antifreezing", "custom_name": "", "dp_id": 103, "time": 1700677460007, "value": 140 }, { "code": "swing", "custom_name": "", "dp_id": 104, "time": 1700073411552, "value": 3 }, { "code": "time_period", "custom_name": "", "dp_id": 105, "time": 1699884863559, "value": 1 }, { "code": "electricity", "custom_name": "", "dp_id": 106, "time": 1699884863559, "value": 0 }, { "code": "curent_pro_time", "custom_name": "", "dp_id": 107, "time": 1700668801980, "value": "EQAWAAMGAwc=" }, { "code": "heatcool_heat_cool", "custom_name": "", "dp_id": 108, "time": 1700073411536, "value": "hc_heat" }, { "code": "antifreezing_switch", "custom_name": "", "dp_id": 109, "time": 1700073411860, "value": true }, { "code": "use_password", "custom_name": "", "dp_id": 110, "time": 1700073411864, "value": false }, { "code": "true_off", "custom_name": "", "dp_id": 111, "time": 1700678542850, "value": false }, { "code": "password", "custom_name": "", "dp_id": 116, "time": 1700073411948, "value": 0 }, { "code": "partial_key_lock", "custom_name": "", "dp_id": 118, "time": 1700073411729, "value": false } ] }, "success": true, "t": 1700678807061, "tid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

I  had try to use https://github.com/rospogrigio/localtuya to control my thermostat , after add last two code into /homeassistant/custom_components/localtuya/climate.py ,it can works

`class LocaltuyaClimate(LocalTuyaEntity, ClimateEntity):
    """Tuya climate device."""

    def __init__(
        self,
        device,
        config_entry,
        switchid,
        **kwargs,
    ):
        """Initialize a new LocaltuyaClimate."""
        super().__init__(device, config_entry, switchid, _LOGGER, **kwargs)
        self._state = None
        self._target_temperature = None
        self._current_temperature = None
        self._hvac_mode = None
        self._preset_mode = None
        self._hvac_action = None
        **self._attr_target_temperature_high = 35.0
        self._attr_target_temperature_low = 15.0**`
