### ISSUE TITLE
Icons Missing/Spelling

### ISSUE THREAD

**Issue by iculookn** [tuya/tuya-smart-life#35]
Just installed this integration and it's working ok.

Under devices, the icons are missing.

it is linking to https://brands.home-assistant.io/smartlife/dark_icon.png, which doesn't exist

The Integration screen is also missing an icon, AND "smartlife" should really be with a Capital "Smart Life"

![image](https://github.com/tuya/tuya-smart-life/assets/8793442/e8e2fb73-5ef8-4647-abcf-d2fed89274f1)

![image](https://github.com/tuya/tuya-smart-life/assets/8793442/972ad4d1-afb8-4784-91d9-92a47f2782e5)

**Comment by gsqqq123** [comment]
The current beta version does not support uploading images. We will have image support in the official release later

**Comment by ssewell** [comment]
> The current beta version does not support uploading images. We will have image support in the official release later

Op is referring to invalid brand icon references, not the ability to upload custom images. The current implementation is referencing a brand/icon that has not been submitted to the [Home Assistant Brands repo](https://github.com/home-assistant/brands/) and thus is showing up as a broken image throughout the Smart Life integration.
