### ISSUE TITLE
Smartlife icon is 404

### ISSUE THREAD

**Issue by M0LTE** [tuya/tuya-smart-life#4]
The integration uses this URL for an icon: https://brands.home-assistant.io/smartlife/icon.png

It is currently 404 so the icon is broken throughout Home Assistant.

**Comment by zlinoliver** [comment]
Thanks for the feedbacks! We plan to release this integration in the [HA official integration](https://www.home-assistant.io/integrations/), and prevent duplication of using the same icon in this custom component version.
