### ISSUE TITLE
Smoke alarm only shows battery state

### ISSUE THREAD

**Issue by SmartHomeFanatic** [tuya/tuya-smart-life#40]
Hi!
Thanks for bringing this official integration without needing to renew cloud access.

I have a LSC smoke detector. In Home Assistant I can only see the battery percentage but not the state of the smoke detector.

**Comment by gsqqq123** [comment]
Can you provide diagnostics file？

**Comment by SmartHomeFanatic** [comment]
@gsqqq123 does this help you?

  "data": {
    "endpoint": "https://apigw.tuyaeu.com",
    "terminal_id": "17006420450440D3CLT",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "61840056c45bbee98e87",
    "name": "Rauchwarnmelder",
    "category": "ywbj",
    "product_id": "cjlutkuuvxnie17o",
    "product_name": "Smoke Alarm",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2022-11-10T09:53:34+00:00",
    "create_time": "2022-11-10T09:53:34+00:00",
    "update_time": "2022-11-10T09:53:34+00:00",
    "function": {},
    "status_range": {
      "battery_state": {
        "type": "Enum",
        "value": {
          "range": [
            "low",
            "middle",
            "high"
          ]
        }
      }
    },
    "status": {
      "battery_state": "high"
    },
    "home_assistant": {
      "name": "Rauchwarnmelder",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:battery",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.rauchwarnmelder_battery_state_2",
            "state": "high",
            "attributes": {
              "icon": "mdi:battery",
              "friendly_name": "Rauchwarnmelder Battery state"
            },
            "last_changed": "2023-11-29T09:58:10.384294+00:00",
            "last_updated": "2023-11-29T09:58:10.384294+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true
  }

**Comment by shihuimiao** [comment]
HA does not support all functions here, only the standard instruction set of the device is supported.
This device only support battery_state.

**Comment by SmartHomeFanatic** [comment]
That's not true. I am using the Tuya IoT connection in parallel at the moment and that one is showing the status of the smoke detector.

See the diagnostic info of the IoT integration of that device

```"home_assistant": {
      "name": "Rauchwarnmelder",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:battery",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.rauchwarnmelder_battery_state",
            "state": "high",
            "attributes": {
              "icon": "mdi:battery",
              "friendly_name": "Rauchwarnmelder Batteriestatus"
            },
            "last_changed": "2023-11-29T09:58:10.229352+00:00",
            "last_updated": "2023-11-29T09:58:10.229352+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "smoke",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.rauchwarnmelder_rauch",
            "state": "off",
            "attributes": {
              "device_class": "smoke",
              "friendly_name": "Rauchwarnmelder Rauch"
            },
            "last_changed": "2023-11-29T09:58:10.128675+00:00",
            "last_updated": "2023-11-29T09:58:10.128675+00:00"
          }
        }

**Comment by shihuimiao** [comment]
sorry Non standard instruction sets are not supported.
