### ISSUE TITLE
PTZ camera is not controllable

### ISSUE THREAD

**Issue by SmartHomeFanatic** [tuya/tuya-smart-life#41]
Hi!

I can see the camera stream and all settings of the camera but I cannot move the camera.

**Comment by gsqqq123** [comment]
Can you provide diagnostics file？

**Comment by SmartHomeFanatic** [comment]
``   "status": {
      "basic_flip": false,
      "basic_osd": true,
      "basic_private": false,
      "motion_sensitivity": 0,
      "basic_nightvision": 0,
      "sd_storge": "989184|9216|979968",
      "sd_status": 1,
      "sd_format": false,
      "movement_detect_pic": "**REDACTED**",
      "ptz_stop": true,
      "sd_format_state": 0,
      "ptz_control": 5,
      "ptz_calibration": true,
      "motion_switch": false,
      "decibel_switch": false,
      "decibel_sensitivity": 0,
      "record_switch": false,
      "record_mode": 2,
      "siren_switch": false,
      "motion_tracking": false,
      "alarm_message": "**REDACTED**",
      "basic_anti_flicker": 1
    },
    "home_assistant": {
      "name": "LSC PTZ Camera",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "camera.lsc_ptz_camera_none",
            "state": "idle",
            "attributes": {
              "access_token": "d13d6d1ee38e95a2ca28d7c3d69bde6dc20f4d3b7a1c99109346a48930fe977",
              "model_name": "LSC PTZ Camera",
              "brand": "smart life",
              "frontend_stream_type": "hls",
              "entity_picture": "**REDACTED**",
              "friendly_name": "LSC PTZ Camera None",
              "supported_features": 2
            },
            "last_changed": "2023-11-29T09:58:10.293841+00:00",
            "last_updated": "2023-11-29T12:17:19.342814+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:volume-vibrate",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.lsc_ptz_camera_sound_detection_densitivity",
            "state": "0",
            "attributes": {
              "options": [
                "0",
                "1"
              ],
              "icon": "mdi:volume-vibrate",
              "friendly_name": "LSC PTZ Camera Sound detection densitivity"
            },
            "last_changed": "2023-11-29T09:58:10.372493+00:00",
            "last_updated": "2023-11-29T09:58:10.372493+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:record-rec",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.lsc_ptz_camera_record_mode",
            "state": "2",
            "attributes": {
              "options": [
                "1",
                "2"
              ],
              "icon": "mdi:record-rec",
              "friendly_name": "LSC PTZ Camera Record mode"
            },
            "last_changed": "2023-11-29T09:58:10.372674+00:00",
            "last_updated": "2023-11-29T09:58:10.372674+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:theme-light-dark",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.lsc_ptz_camera_night_vision",
            "state": "0",
            "attributes": {
              "options": [
                "0",
                "1",
                "2"
              ],
              "icon": "mdi:theme-light-dark",
              "friendly_name": "LSC PTZ Camera Night vision"
            },
            "last_changed": "2023-11-29T09:58:10.372854+00:00",
            "last_updated": "2023-11-29T09:58:10.372854+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:image-outline",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.lsc_ptz_camera_anti_flicker",
            "state": "1",
            "attributes": {
              "options": [
                "0",
                "1",
                "2"
              ],
              "icon": "mdi:image-outline",
              "friendly_name": "LSC PTZ Camera Anti-flicker"
            },
            "last_changed": "2023-11-29T09:58:10.373030+00:00",
            "last_updated": "2023-11-29T09:58:10.373030+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:motion-sensor",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.lsc_ptz_camera_motion_detection_sensitivity",
            "state": "0",
            "attributes": {
              "options": [
                "0",
                "1",
                "2"
              ],
              "icon": "mdi:motion-sensor",
              "friendly_name": "LSC PTZ Camera Motion detection sensitivity"
            },
            "last_changed": "2023-11-29T09:58:10.373240+00:00",
            "last_updated": "2023-11-29T09:58:10.373240+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "siren.lsc_ptz_camera_siren",
            "state": "off",
            "attributes": {
              "friendly_name": "LSC PTZ Camera Siren",
              "supported_features": 3
            },
            "last_changed": "2023-11-29T09:58:10.387677+00:00",
            "last_updated": "2023-11-29T09:58:10.387677+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:microphone-outline",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_sound_detection",
            "state": "off",
            "attributes": {
              "icon": "mdi:microphone-outline",
              "friendly_name": "LSC PTZ Camera Sound detection"
            },
            "last_changed": "2023-11-29T09:58:10.400340+00:00",
            "last_updated": "2023-11-29T09:58:10.400340+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:record-rec",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_video_recording",
            "state": "off",
            "attributes": {
              "icon": "mdi:record-rec",
              "friendly_name": "LSC PTZ Camera Video recording"
            },
            "last_changed": "2023-11-29T09:58:10.400532+00:00",
            "last_updated": "2023-11-29T09:58:10.400532+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:eye-off",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_privacy_mode",
            "state": "off",
            "attributes": {
              "icon": "mdi:eye-off",
              "friendly_name": "LSC PTZ Camera Privacy mode"
            },
            "last_changed": "2023-11-29T09:58:10.400712+00:00",
            "last_updated": "2023-11-29T09:58:10.400712+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:flip-horizontal",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_flip",
            "state": "off",
            "attributes": {
              "icon": "mdi:flip-horizontal",
              "friendly_name": "LSC PTZ Camera Flip"
            },
            "last_changed": "2023-11-29T09:58:10.400891+00:00",
            "last_updated": "2023-11-29T09:58:10.400891+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:watermark",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_time_watermark",
            "state": "on",
            "attributes": {
              "icon": "mdi:watermark",
              "friendly_name": "LSC PTZ Camera Time watermark"
            },
            "last_changed": "2023-11-29T09:58:10.401068+00:00",
            "last_updated": "2023-11-29T09:58:10.401068+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:motion-sensor",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_motion_tracking",
            "state": "off",
            "attributes": {
              "icon": "mdi:motion-sensor",
              "friendly_name": "LSC PTZ Camera Motion tracking"
            },
            "last_changed": "2023-11-29T09:58:10.401281+00:00",
            "last_updated": "2023-11-29T09:58:10.401281+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": "mdi:motion-sensor",
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.lsc_ptz_camera_motion_alarm",
            "state": "off",
            "attributes": {
              "icon": "mdi:motion-sensor",
              "friendly_name": "LSC PTZ Camera Motion alarm"
            },
            "last_changed": "2023-11-29T09:58:10.401470+00:00",
            "last_updated": "2023-11-29T09:58:10.401470+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": false
  }
}

**Comment by SmartHomeFanatic** [comment]
The camera is capable of being controlled remotely (pan & tilt)

**Comment by shihuimiao** [comment]
HA only supports a subset of features, Not supported move the camera

**Comment by SmartHomeFanatic** [comment]
Of course this is supported. There are lots of integrations that support pan&tilt.
Nevermind, disabling the integration now and sticking with the IoT based one.
