### ISSUE TITLE
No Data Showing for ITC 308 Wifi

### ISSUE THREAD

**Issue by StodgyWaif** [tuya/tuya-smart-life#43]
I have 2 of these units. Both are set up and working properly in the Smart Life App.
I added them to Home Assistant and only 1 of them is showing data.

![image](https://github.com/tuya/tuya-smart-life/assets/25680410/35943d6a-3f2c-4602-9881-d75b1d84b749)
![image](https://github.com/tuya/tuya-smart-life/assets/25680410/18f62ba8-88bf-415e-a5f3-3e302b01fd45)

EDIT: I forgot to mention I installed this via HACS
EDIT2: I just checked the device update page on the app for both units.

The working unit says:
Main Module: V3.1.4
MCU Module: V1.0.0

The non-working unit says:
Main Module: V2.5.2
MCU Module: V1.0.0

Both say no updates available.
Is there a way to update the non-working unit to the same version?

**Comment by shihuimiao** [comment]
Can you provide diagnostics file about of These devices？

**Comment by StodgyWaif** [comment]
Thank you for responding.
Where do I get the diagnostics file from?

**Comment by StodgyWaif** [comment]
[smartlife-c1a55c2907276bfa676b3536526166e9-Mini Fridge-d6e17d5007cbe5e2ac4c12cf50b7133e.json.txt](https://github.com/tuya/tuya-smart-life/files/13536905/smartlife-c1a55c2907276bfa676b3536526166e9-Mini.Fridge-d6e17d5007cbe5e2ac4c12cf50b7133e.json.txt)

**Comment by shihuimiao** [comment]
> diagnostics file

the non-working one product has none Standard Instruction Set, you can view the diagnostics file about  "status_range" and  "status" That part of the data is empty

**Comment by StodgyWaif** [comment]
Somehow this just started working on it's own recently.
I'm assuming an update fixed it.
