### ISSUE TITLE
Problems related to the category of devices supported : clkg

### ISSUE THREAD

**Issue by ThePowerVoid** [tuya/tuya-smart-life#44]
Hello,
My device is not supported, so it has to be part of the category clkg
![image](https://github.com/tuya/tuya-smart-life/assets/25184630/03e9e4c1-28d1-4d16-8ac1-a2189c206e49)
![image](https://github.com/tuya/tuya-smart-life/assets/25184630/4507e6eb-5a16-4c1a-a54a-cdc6c2dd47d4)

Could you help me with this problem?

Thanks

**Comment by gsqqq123** [comment]
The product features configured by the manufacturer of your device are not standardized, so they cannot be used in HA
