### ISSUE TITLE
Missing `add_ele` (cumulative kWh) sensor for power metering socket.

### ISSUE THREAD

**Issue by jarthod** [tuya/tuya-smart-life#47]
First of all, thanks for this new integration which is MUCH easier than https://github.com/tuya/tuya-home-assistant :clap: 

I just tried it because I was missing some power metrics in my circuit breakers and was happy to find them with this integration :) the connection worked well and I have more metrics than with https://github.com/tuya/tuya-home-assistant so far so good.

I only noticed **one** missing sensor in my case (`add_ele`) with some connected outlets with power metering (Konyks Priska+ Mini in my case). The `add_ele` attribute is returning the cumulative kWh, very useful for accurate energy metering.

I checked the code and it is supported for circuit breaker: https://github.com/tuya/tuya-smart-life/blob/33a6ecad44adf2ac2916671f5894c1bcc568145a/custom_components/smartlife/sensor.py#L821-L828
I do have one of those and it's working so cool :sunglasses: (see the kWh number in the sensors, along the 3 classic others W, V, A)
![image](https://github.com/tuya/tuya-smart-life/assets/201687/471ea834-3fcb-4356-ad74-dde0914bd6cb)

But it's not supported for outlets (only W, V, A here):
![image](https://github.com/tuya/tuya-smart-life/assets/201687/34785a97-8fdf-4a00-8e36-f7f0c297d205)

While the attribute is available the same way, I can see it in Tuya IoT debug UI:
![image](https://github.com/tuya/tuya-smart-life/assets/201687/e89dfac9-24da-438d-b167-744c171cd514)

So I would like to request for this attribute to be added for outlets too, in `cz` or `pc` I guess? or maybe `kg`.
FTR this sensor (`add_ele`) was also missing in the native Tuya integration so it's not a regression, just would be a nice addition :+1: otherwise I can't use my 3 power metering outlets for energy mesurement in the dashboard.

Thanks, and sorry if my issue is missing important details, I'm new to HA so let me know if there's more debug info/logs that would be useful.

**Comment by shihuimiao** [comment]
Please provide the diagnostics file, we will check the product.

**Comment by jarthod** [comment]
Actually I noticed a couple other issue with both my circuit breakers (already "supported") and outlets (for which I added "support" with the previously shown copy-pasted config):

1. Sometimes the `add_ele` event is missing from the time series, leading to inacurrate results. For example here between 01:00 and 02:00 I have no data point (if I hover I can only see one at 00:58 and one at 02:28):
![image](https://github.com/tuya/tuya-smart-life/assets/201687/99fc4464-7310-4a38-a4dd-84d2258924fe)
While the consumption was definitely not 0 and the device seems to be sending those events at least every 30 minutes:
![image](https://github.com/tuya/tuya-smart-life/assets/201687/ab349988-4f66-4935-81ae-4882e7277ba9)
(screenshot from Tuya IoT platform for reference as I don't know where else I can find this).
This happen also with my circuit breakers but is more likely when the value is very stable, so I suspect some intentional "deduplication" logic here is removing "duplicate" entries, thinking it wouldn't change the end result but it does matter as this is only a **delta**.

2. I also found warnings in my logs that the sensor is using "TOTAL_INCREASING" while the values is not increasing, and this is very true, this value is only a delta of kWh since previous event, so it's definitely not a total increasing counter. And this might be the reason for 1 (because if it were really a total increasing counter, not storing duplicates would be acceptable). Unfortunatly I don't know to improve this because the only other option if it's not a globally increasing counter is "measurement", but this is apparently not OK with the "energy" type: `2023-12-03 16:19:47.375 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.bureau_add_ele (<class 'custom_components.smartlife.sensor.SmartLifeSensorEntity'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the author of the 'smartlife' custom integration`

So I'm not sure how we are supposed to implement sensor values in kWh **delta** like this one. I was a bit suprised to noticed this type of counter which is implemented in many outlets and counter for years hasn't any obvious  implementation in HA? I'm currently trying to fiddle with some https://www.home-assistant.io/integrations/utility_meter/ and https://www.home-assistant.io/integrations/integration/ simply to get an accurate chart of consumption per hour like anybody would want (like in the Tuya app) but I couldn't get anything correct so far and I feel like I'm fighting with the system here. Maybe I'm missing something obvious here?

At the moment I changed the type to "total" instead of "total_increasing" because it's definitely not increasing, this way I don't have any warning, but this is still not correct because it's not a total and I guess it'll still create problems (like the deduplication).

**Comment by shihuimiao** [comment]
> Yes sure, I guess it's [this one](https://github.com/tuya/tuya-smart-life/files/13523740/smartlife-f82d6ab5edded4f588fe1d33509dc5aa-Bureau-05f164dc78c4fa84daae68f5c5fb414b.json.txt)? let me know if not ^^

The category of your device is "cz", Not Supported add_ele.

Currently only supported the category of "dlq".

You can read the code.

**Comment by jarthod** [comment]
Mmm yes saw and I did look at the code, that's exactly why I'm writting this ticket suggesting to add `add_ele` support. Because this outlet (and many others) does support it ^^

**Comment by NickStallman** [comment]
+1 for add_ele support.

In my case I have:
```
    "product_id": "bezptefgpqmax74x",
    "product_name": "6920HA",
```
Diagnostics attached.
[smartlife-91f1e2d812d37fe02c3f041baf262bc3-Laundry socket-16fdc198c9c915024680d18e86a2dd56.json.txt](https://github.com/tuya/tuya-smart-life/files/13914770/smartlife-91f1e2d812d37fe02c3f041baf262bc3-Laundry.socket-16fdc198c9c915024680d18e86a2dd56.json.txt)
