### ISSUE TITLE
Unable to link via Smart Life

### ISSUE THREAD

**Issue by mayankraichura** [tuya/tuya-smart-life#5]
I've had all my devices on the Smart Life app for a couple of years now.

1. I followed the instructions and installed the `smartlife` custom component. 
2. Tried to set up the `smartlife` integration by entering the user code and then scanning the QR code.

The 2nd step fails with `ILLEGAL_PARAM_ERROR`. If it helps, my server is in India.

![WhatsApp Image 2023-10-26 at 18 42 07](https://github.com/tuya/tuya-smart-life/assets/2023368/79fae844-c7a0-4e0a-a4c5-face55f784a8)

**Comment by uddinkayyum** [comment]
Facing same issue ILLEGAL_PARAM_ERROR when using an account with India data center in smartlife app. But using an account with switzerland location, resolve my issue.
After pairing, Even devices are connected to homeassistant but can't control it.
![Screenshot from 2023-10-30 14-45-27](https://github.com/tuya/tuya-smart-life/assets/94560388/a30cd07e-8978-4121-a002-594a719e40b1)
![Screenshot from 2023-10-30 14-45-08](https://github.com/tuya/tuya-smart-life/assets/94560388/883c8631-ee2d-4a57-b8bf-2c44f698dc7e)

**Comment by shihuimiao** [comment]
Please log in again and see if there are any further issues.

**Comment by mayankraichura** [comment]
Thank you. I'm able to log in now. Thanks a lot.
