### ISSUE TITLE
Device found but no entities

### ISSUE THREAD

**Issue by peterdlakatos** [tuya/tuya-smart-life#6]
Hi there,

I have a Tuya Neo NAS-AB02WT Siren w integrated temperature and humidity sensor.
When I add this integration, the device itself is found, but no entities are listed.
I can read the sensor values and control the alarm from the Smart Life app. I also see the sensor values in the [Tuya IoT Platform](https://iot.tuya.com/).
Same thing happened when I've tried the "old" [tuya integration](https://www.home-assistant.io/integrations/tuya/).
The device is named as "unsupported", however it's category is "wsdcg", which appears in several places in the code.

![2023-10-26_20h04_28](https://github.com/tuya/tuya-smart-life/assets/5502104/757a7b8e-92b0-4b60-9cdc-f74c7db6d885)
![2023-10-26_20h12_26](https://github.com/tuya/tuya-smart-life/assets/5502104/f5da5dba-7bd8-4c20-832c-0db6473bb93b)
[smartlife-274cf8a08cfb6478192e440284f1524b-Siren1234-5023e25f76e3ee53d74049401edf8a4e.json.txt](https://github.com/tuya/tuya-smart-life/files/13181305/smartlife-274cf8a08cfb6478192e440284f1524b-Siren1234-5023e25f76e3ee53d74049401edf8a4e.json.txt)

I'm quite new in this topic, but if you point me to the right direction, I'm happy to contribute.
Thank you for the support in advance!
Péter

**Comment by shihuimiao** [comment]
This product does not contain standard features. You can view the diagnostics file.

**Comment by peterdlakatos** [comment]
Hi there,

What does "standard feature" means in this context and what should I search for in the diagnostics file? Is there a public documentation regarding that?

I'm quite new in this topic, but if you point me to the right direction, I'm happy to contribute.

Péter
