### ISSUE TITLE
Lighting devices throwing unsupported operand TypeError

### ISSUE THREAD

**Issue by osaerisxero** [tuya/tuya-smart-life#8]
Lighting devices in rev [e0312c4](https://github.com/tuya/tuya-smart-life/commit/e0312c40a596e39ab8da6712c11d39840e872e52) are throwing `TypeError: unsupported operand type(s) for -: 'str' and 'int'` during what I presume is instantiation.  In util.py:remap_value(), force-casting `value` to a float with `float(value)` resolves the issue.  I have not attempted to trace back why `value` is being passed to `remap_value()` as a string yet.

**Comment by osaerisxero** [comment]
[postfix_smartlife-36f301675e032815d116fe9ff06ad6b8-New Billy Office Strip-769436b8c0f681c48408b520dda924f4.json.txt](https://github.com/tuya/tuya-smart-life/files/13211745/postfix_smartlife-36f301675e032815d116fe9ff06ad6b8-New.Billy.Office.Strip-769436b8c0f681c48408b520dda924f4.json.txt)
[prefix_smartlife-36f301675e032815d116fe9ff06ad6b8-New Billy Office Strip-769436b8c0f681c48408b520dda924f4.json.txt](https://github.com/tuya/tuya-smart-life/files/13211746/prefix_smartlife-36f301675e032815d116fe9ff06ad6b8-New.Billy.Office.Strip-769436b8c0f681c48408b520dda924f4.json.txt)


And since I took the time to rebreak it, here's the full stack trace:



Logger: homeassistant.loader
Source: loader.py:838
First occurred: 10:33:19 PM (15 occurrences)
Last logged: 10:33:19 PM

    Unexpected exception importing platform custom_components.smartlife.number
    Unexpected exception importing platform custom_components.smartlife.vacuum
    Unexpected exception importing platform custom_components.smartlife.siren
    Unexpected exception importing platform custom_components.smartlife.light
    Unexpected exception importing platform custom_components.smartlife.switch

Traceback (most recent call last):
```
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/smartlife/binary_sensor.py", line 20, in <module>
    from .base import SmartLifeEntity
  File "/config/custom_components/smartlife/base.py", line 17, in <module>
    from .util import remap_value
  File "/config/custom_components/smartlife/util.py", line 16
    return (value - from_min) / (from_max - from_min)) * (to_max - to_min) + to_min
                                                     ^
SyntaxError: unmatched ')'
```

**Comment by shihuimiao** [comment]
https://github.com/tuya/tuya-smart-life/blob/main/custom_components/smartlife/util.py
     return ((value - from_min) / (from_max - from_min)) * (to_max - to_min) + to_min
Checked the code and found no problem. Pull down the master branch and restart it

**Comment by shihuimiao** [comment]
Fixed. Please download the smartlife plugin code again and integrate it again

**Comment by osaerisxero** [comment]
Yep, that looks like it got it.

Thanks!
