### ISSUE TITLE
Car charger not working in HA

### ISSUE THREAD

**Issue by ivik** [tuya/tuya-smart-life#82]
# The problem

I have a car charges that works fine in Smart life app but not in HA (EU_230V_16A(EA) (unsupported)
by smartlife)

## Your Environment

Newest version of everything, all up to date.

* tuya-device-sharing-sdk Version used: 0.1.9
* Device diagnostic file:

[smartlife-b931075df5b752acbe5a69a76a6fae0f-EU_230V_16A(EA)-386995b676a2c05df88e77ccd369ee33.json.txt](https://github.com/tuya/tuya-smart-life/files/13891037/smartlife-b931075df5b752acbe5a69a76a6fae0f-EU_230V_16A.EA.-386995b676a2c05df88e77ccd369ee33.json.txt)

**Comment by shihuimiao** [comment]
the category of "qccdz" is not supported

**Comment by ivik** [comment]
Ok, is there anything else I could do? Or is my best bet to try localtuya or tuyalocal and see if I can manually get it working?

**Comment by shihuimiao** [comment]
If you have the development ability, you can try developing it yourself.

**Comment by ivik** [comment]
Sorry don't know any pyton, at least not for now, but hopefully soon.
