### ISSUE TITLE
Smart Light Unavailable on Home Assistant, Working Fine on Smart Life App

### ISSUE THREAD

**Issue by guaycuru** [tuya/tuya-smart-life#95]
# The problem
I just downloaded and configured the Smart Life integration on Home Assistant. I have a Smart Light that is working fine in the Smart Life app, but show as "Unavailable" in Home Assistant. Restarting Home Assistant did not fix it. Also tried removing the integration and configuring it again, with same results.
Edit: This same smart light was working fine with the "Tuya" integration.

## Your Environment

Include as many relevant details about the environment you experienced the bug in

* tuya-device-sharing-sdk Version used: 0.1.9
* Smart Life Integration version a3aaeb4
* Device diagnostic file: 
[smartlife-b9eb637932a8184db849ef1c107320e0-Luz Escritorio Fe-30647b7077a04f26a3b54baf586280e1.json.txt](https://github.com/tuya/tuya-smart-life/files/14010514/smartlife-b9eb637932a8184db849ef1c107320e0-Luz.Escritorio.Fe-30647b7077a04f26a3b54baf586280e1.json.txt)

![image](https://github.com/tuya/tuya-smart-life/assets/1985884/4159968a-1945-403e-96ba-c5323b3f0edd)

![image](https://github.com/tuya/tuya-smart-life/assets/1985884/3e0f3662-ee95-4786-b5c0-abdb7e4b028b)

**Comment by shihuimiao** [comment]
The product does not have a standard instruction "switch"

**Comment by guaycuru** [comment]
That doesn't make sense, as that same exact product was working fine with the "Tuya" integration

**Comment by shihuimiao** [comment]
sorry, your Device diagnostic file shows "online": false, so the device is Unavailable

**Comment by guaycuru** [comment]
That's weird because it shows as online in the Smart Life app.
Anyway, for some reason today it started working. I didn't change anything so that's a mystery. Thank you anyway..
